Enhance gRPC log appender to allow layout pattern (#6403)

diff --git a/.github/workflows/e2e.istio.yaml b/.github/workflows/e2e.istio.yaml
--- a/.github/workflows/e2e.istio.yaml
+++ b/.github/workflows/e2e.istio.yaml
@@ -48,6 +48,17 @@ jobs:
         with:
           submodules: true
 
+      - name: Check Unintended Changes
+        run: |
+          echo "::group::Check sw.version"
+          sudo apt install -y -q xmlstarlet
+          SW_VERSION=$(xmlstarlet sel -N pom=http://maven.apache.org/POM/4.0.0 -t -v "/pom:project/pom:properties/pom:sw.version" test/e2e/pom.xml)
+          if [[ "$(echo $(echo $SW_VERSION))" != "" ]]; then
+            echo "::error Please don't submit the change of sw.version in test/e2e/pom.xml"
+            exit 1
+          fi
+          echo "::endgroup::"
+
       - name: Set Skip Env Var
         uses: ./.github/actions/skip
 
@@ -132,7 +143,12 @@ jobs:
           export WEBAPP_HOST=127.0.0.1
           export WEBAPP_PORT=8080
 
-          ./mvnw --batch-mode -f test/e2e/pom.xml -am -DfailIfNoTests=false verify -Dit.test=org.apache.skywalking.e2e.mesh.ALSE2E
+          export SW_VERSION=$(./mvnw -q -DforceStdout -N org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version)
+
+          ./mvnw -DskipTests -N install
+          ./mvnw -f apm-application-toolkit -DskipTests -am install
+
+          ./mvnw --batch-mode -f test/e2e/pom.xml -am -DfailIfNoTests=false -Dsw.version=${SW_VERSION} verify -Dit.test=org.apache.skywalking.e2e.mesh.ALSE2E
 
       - name: Logs
         if: ${{ failure() }}
@@ -161,6 +177,17 @@ jobs:
       - uses: actions/checkout@v2
         with:
           submodules: true
+
+      - name: Check Unintended Changes
+        run: |
+          echo "::group::Check sw.version"
+          sudo apt install -y -q xmlstarlet
+          SW_VERSION=$(xmlstarlet sel -N pom=http://maven.apache.org/POM/4.0.0 -t -v "/pom:project/pom:properties/pom:sw.version" test/e2e/pom.xml)
+          if [[ "$(echo $(echo $SW_VERSION))" != "" ]]; then
+            echo "Please don't submit the change of sw.version in test/e2e/pom.xml"
+            exit 1
+          fi
+          echo "::endgroup::"
 
       - name: Set Skip Env Var
         uses: ./.github/actions/skip
@@ -246,7 +273,12 @@ jobs:
           export WEBAPP_HOST=127.0.0.1
           export WEBAPP_PORT=8080
 
-          ./mvnw --batch-mode -f test/e2e/pom.xml -am -DfailIfNoTests=false verify -Dit.test=org.apache.skywalking.e2e.mesh.MetricsServiceE2E
+          export SW_VERSION=$(./mvnw -q -DforceStdout -N org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version)
+
+          ./mvnw -DskipTests -N install
+          ./mvnw -f apm-application-toolkit -DskipTests -am install
+
+          ./mvnw --batch-mode -f test/e2e/pom.xml -am -DfailIfNoTests=false -Dsw.version=${SW_VERSION} verify -Dit.test=org.apache.skywalking.e2e.mesh.MetricsServiceE2E
 
       - name: Logs
         if: ${{ failure() }}
