fix workflow
Signed-off-by: Megrez Lu <lujiajing1126@gmail.com>

diff --git a/.github/workflows/e2e.banyandb.yaml b/.github/workflows/e2e.banyandb.yaml
--- a/.github/workflows/e2e.banyandb.yaml
+++ b/.github/workflows/e2e.banyandb.yaml
@@ -13,7 +13,7 @@
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
-name: E2E
+name: BanyanDB
 
 on:
   pull_request:
@@ -24,40 +24,42 @@ env:
   SW_AGENT_JDK_VERSION: 8
 
 jobs:
-  StoragePluginBanyanDB:
-    name: Storage Plugin/BanyanDB
+  StoragePlugin:
+    if: (github.event_name == 'schedule' && github.repository == 'apache/skywalking') || (github.event_name != 'schedule')
+    name: Storage Plugin
     runs-on: ubuntu-latest
+    timeout-minutes: 90
     steps:
       - uses: actions/checkout@v2
         with:
           submodules: true
       - name: Build Docker Image
-      shell: bash
-      env:
-        SKIP_TEST: "true"
-      run: |
-        echo "::group::Build Docker Image"
-        # Retry one more time due to frequent "maven connection reset"
-        (make docker || make docker) && (ES_VERSION=es7 TAG=latest-es7 make docker.oap || ES_VERSION=es7 TAG=latest-es7 make docker.oap)
-        echo "::endgroup::"
+        shell: bash
+        env:
+          SKIP_TEST: "true"
+        run: |
+          echo "::group::Build Docker Image"
+          # Retry one more time due to frequent "maven connection reset"
+          (make docker || make docker) && (ES_VERSION=es7 TAG=latest-es7 make docker.oap || ES_VERSION=es7 TAG=latest-es7 make docker.oap)
+          echo "::endgroup::"
       - name: Copy Dist Package
-      shell: bash
-      run: |
-        echo "::group::Copy Dist Package to test/e2e"
-        cp -R dist test/e2e/
-        echo "::endgroup::"
-      - uses: apache/skywalking-infra-e2e@de5be41596f27867a15ab75dbad97ea538d863b8
-        with:
-          e2e-file: test/e2e/e2e-test/docker/storage/banyandb/e2e.yaml
+        shell: bash
+        run: |
+          echo "::group::Copy Dist Package to test/e2e"
+          cp -R dist test/e2e/
+          echo "::endgroup::"
       - name: Prepare E2E Test
-      shell: bash
-      run: |
-        echo "::group::Install SNAPSHOT apm-application-toolkit"
-        ./mvnw -DskipTests -N install
-        ./mvnw -f apm-application-toolkit -DskipTests -am install
-        echo "::endgroup::"
+        shell: bash
+        run: |
+          echo "::group::Install SNAPSHOT apm-application-toolkit"
+          ./mvnw -DskipTests -N install
+          ./mvnw -f apm-application-toolkit -DskipTests -am install
+          echo "::endgroup::"
 
-        echo "::group::Prepre E2E Test"
-        SW_VERSION=$(./mvnw -q -DforceStdout -N org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version)
-        ./mvnw --batch-mode -f test/e2e/pom.xml -am -DfailIfNoTests=false -Dsw.version=${SW_VERSION} package
-        echo "::endgroup::"
+          echo "::group::Prepre E2E Test"
+          SW_VERSION=$(./mvnw -q -DforceStdout -N org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version)
+          ./mvnw --batch-mode -f test/e2e/pom.xml -am -DfailIfNoTests=false -Dsw.version=${SW_VERSION} package
+          echo "::endgroup::"
+      - uses: apache/skywalking-infra-e2e@de5be41596f27867a15ab75dbad97ea538d863b8
+          with:
+            e2e-file: test/e2e/e2e-test/docker/storage/banyandb/e2e.yaml
